ENCHANTMENTS := [
    "Move Speed Bonus",
    "Additional Move Speed",
    "Strength",
    "Agility",
    "Dexterity",
    "Will",
    "Knowledge",
    "Vigor",
    "Armor Penetration",
    "Physical Damage Bonus",
    "Physical Power",
    "Magic Penetration",
    "Magical Damage Bonus",
    "Magical Power",
    "Additional Armor Rating",
    "Magic Resistance",
    "Physical Damage Reduction",
    "Magical Damage Reduction",
    "Action Speed",
    "Regular Interaction Speed",
    "Spell Casting Speed",
    "Magical Healing",
    "Memory Capacity Add",
    "Luck",
    "Max Health",
    "Armor Rating",
    "Max Health Bonus",
    "Additional Physical Damage",
    "True Physical Damage",
    "Additional Weapon Damage",
    "True Magical Damage",
    "Additional Magical Damage",

]

ITEMS := [
    "Arming Sword",
    "Crystal Sword",
    "Falchion",
    "Longsword",
    "Rapier",
    "Short Sword",
    "Viking Sword",

    "Blade of Righteousness",
    "Demon's Glee",
    "Divine Blade",
    "Divine Short Sword",
    "Falchion of Honor",
    "Golden Viking Sword",
    "Short Sword of Righteousness",
    "Sterling Blade",

    "Boneshaper",
    "Divine Rod",
    "Divine Staff",
    "Light Bringer",
    "Flanged Mace",
    "Rod of Righteousness",
    "Staff of Righteousness",
    "Sterling Rod",
    "Sterling Staff",

    "Castillon Dagger",
    "Kris Dagger",
    "Rondel Dagger",
    "Stiletto Dagger",

    'Dagger of Righteousness',
    'Divine Dagger',
    'Sterling Dagger',
    'Throwing Knife',

    "Bardiche",
    "Halberd",
    "Spear",

    "Spear of Rot",

    'Battle Axe',
    'Double Axe',
    'Felling Axe',
    'Hatchet',
    "Horseman's Axe",

    "Axe of Righteousness",
    "Divine Axe",
    "Francisca Axe",
    "Golden Felling Axe",
    "Sterling Axe",

    "Longbow",
    "Recurve Bow",
    "Survival Bow",

    "Crossbow",
    "Hand Crossbow",
    "Windlas Crossbow",

    "Ceremonial Staff",
    "Crystal Ball",
    "Crystal Sword",
    "Magic Staff",
    "Spellbook",

    "Buckler",
    "Heater Shield",
    "Pavise",
    "Round Shield",

    "Armet",
    "Barbuta Helm",
    "Chapel De Fer",
    "Chaperon",
    "Cobalt Chapel De Fer",
    "Cobalt Hat",
    "Cobalt Hood",
    "Cobalt Viking Helm",
    "Copperlight Kettle Hat",
    "Copperlight Shadow Hood",
    "Copperlight Straw Hat",
    "Cowl of Darkness",
    "Crusader Helm",
    "Darkgrove Hood",
    "Dread Hood",
    "Elkwood Crown",
    "Feathered Hat",
    "Forest Hood",
    "Gjermundbu",
    "Golden Armet",
    "Golden Gjermundbu",
    "Golden Hounskull",
    "Golden Leaf Hood",
    "Golden Scarf",
    "Great Helm",
    "Hounskull",
    "Kettle Hat",
    "Leather Bonnet",
    "Leather Cap",
    "Norman Nasal Helm",
    "Occultist Hood",
    "Open Sallet",
    "Ranger Hood",
    "Rogue Cowl",
    "Rubysilver Barbuta Helm",
    "Rubysilver Cap",
    "Rubysilver Hood",
    "Sallet",
    "Shadow Hood",
    "Shadow Mask",
    "Spangenhelm",
    "Straw Hat",
    "Topfhelm",
    "Viking Helm",
    "Visored Barbuta Helm",
    "Visored Sallet",
    "Wizard Hat",
    "Adventurer Tunic",
    "Champion Armor",
    "Cobalt Frock",
    "Cobalt Regal Gambeson",
    "Cobalt Templar Armor",
    "Copperlight Attire",
    "Copperlight Outfit",
    "Copperlight Sanctum Plate Armor",
    "Copperlight Tunic",
    "Crusader Armor",
    "Dark Cuirass",
    "Dark Plate Armor",
    "Darkgrove Robe",
    "Doublet",
    "Fine Cuirass",
    "Frock",
    "Golden Padded Tunic",
    "Golden Plate",
    "Golden Robe",
    "Grand Brigandine",
    "Heavy Gambeson",
    "Light Aketon",
    "Marauder Outfit",
    "Mystic Vestments",
    "Northern Full Tunic",
    "Occultist Robe",
    "Occultist Tunic",
    "Oracle Robe",
    "Ornate Jazerant",
    "Padded Tunic",
    "Pourpoint",
    "Regal Gambeson",
    "Ritual Robe",
    "Robe of Darkness",
    "Rubysilver Cuirass",
    "Rubysilver Doublet",
    "Rubysilver Vestments",
    "Studded Leather",
    "Templar Armor",
    "Tri-Pelt Doublet",
    "Tri-Pelt Northern Full Tunic",
    "Troubadour Outfit",
    "Wanderer Attire",
    "Warden Outfit",
    "Bardic Pants",
    "Brave Hunter's Pants",
    "Cloth Pants",
    "Cobalt Plate Pants",
    "Cobalt Trousers",
    "Copperlight Leggings",
    "Copperlight Pants",
    "Copperlight Plate Pants",
    "Dark Leather Leggings",
    "Demonclad Leggings",
    "Golden Chausses",
    "Golden Leggings",
    "Golden Plate Pants",
    "Heavy Leather Leggings",
    "Leather Chausses",
    "Leather Leggings",
    "Loose Trousers",
    "Occultist Pants",
    "Padded Leggings",
    "Plate Pants",
    "Rubysilver Leggings",
    "Rubysilver Plate Pants",
    "Wolf Hunter Leggings",
    "Cobalt Heavy Gauntlet",
    "Cobalt Leather Gloves",
    "Copperlight Gauntlets",
    "Copperlight Riveted Gloves",
    "Demon Grip Gloves",
    "Elkwood Gloves",
    "Gloves of Utility",
    "Golden Gauntlets",
    "Golden Gloves",
    "Gravewolf Gloves",
    "Heavy Gauntlets",
    "Leather Gloves",
    "Light Gauntlets",
    "Mystic Gloves",
    "Rawhide Gloves",
    "Reinforced Gloves",
    "Riveted Gloves",
    "Rubysilver Gauntlets",
    "Rubysilver Rawhide Gloves",
    "Runestone Gloves",
    "Adventurer Boots",
    "Buckled Boots",
    "Cobalt Lightfoot Boots",
    "Cobalt Plate Boots",
    "Copperlight Lightfoot Boots",
    "Copperlight Plate Boots",
    "Darkleaf Boots",
    "Dashing Boots",
    "Forest Boots",
    "Foul Boots",
    "Golden Boots",
    "Golden Plate Boots",
    "Heavy Boots",
    "Laced Turnshoe",
    "Lightfoot Boots",
    "Low Boots",
    "Occultist Boots",
    "Old Shoes",
    "Plate Boots",
    "Rubysilver Adventurer Boots",
    "Rubysilver Plate Boots",
    "Rugged Boots",
    "Shoes of Darkness",
    "Stitched Turnshoe",
    "Turnshoe",
    "Wizard Shoes",
    "Adventurer Cloak",
    "Cloak of Darkness",
    "Golden Cloak",
    "Mercurial Cloak",
    "Radiant Cloak",
    "Splendid Cloak",
    "Tattered Cloak",
    "Vigilant Cloak",
    "Watchman Cloak",

    "Ring of Courage",
    "Ring of Quickness",
    "Ring of Resolve",
    "Ring of Vitality",
    "Ring of Wisdom",
    "Ring of Finesse",
    "Ring of Survival",
    "Grimsmile Ring",

    "Badger Pendant",
    "Bear Pendant",
    "Fangs of Death Necklace",
    "Fox Pendant",
    "Frost Amulet",
    "Monkey Pendant",
    "Necklace of Peace",
    "Owl Pendant",
    "Ox Pendant",
    "Phoenix Choker",
    "Rat Pendant",
    "Torq of Soul",
    "Wind Locket",

    "Lockpick",
    "Froststone Ore", 
    "Froststone Ingot",
    "Wolf Pelt",
    "Bone",
    "Lantern",
    "Troll Pelt",
    "Troll's Blood",
    "Throwing Knife",
    "Bandage",
    "Potion of Healing",
    "Magic Protection Potion",
    "Potion of Protection",
    "Potion of Invisibility",
    "Explosive Bottle",
    "Gold Ore",
    "Gold Ingot",
    "Surgical Kit",
    "Golden Key",
    "Lyre",
    "Enchanted Dark Fabric",


    ]
